name: Python

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create artifact directory
        run: mkdir -p path/to/artifact

      - name: Run Python script and save output
        run: |
          echo hello > path/to/artifact/${{ matrix.python-version }}.txt
          python -c "import sys; print(sys.version)" >> path/to/artifact/${{ matrix.python-version }}.txt

      - name: Upload artifact for Python ${{ matrix.python-version }}
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact-${{ matrix.python-version }}
          path: path/to/artifact/${{ matrix.python-version }}.txt
